--liquibase formatted sql

--changeset admin:7-add-extended-skill-dictionary
--comment: Adds extended IT skills dictionary: Языки программирования, related technologies, general IT technologies.

INSERT INTO skill_group (name)
SELECT v.name
FROM (
         VALUES
             ('Языки программирования'),
             ('Бекенд фреймворки'),
             ('Фронтенд фреймворки'),
             ('Мобильные фреймворки'),
             ('Хранилища'),
             ('Интеграции'),
             ('SRE'),
             ('ML'),
             ('QA'),
             ('Security'),
             ('Архитектура'),
             ('Инструменты')
     ) AS v(name)
WHERE NOT EXISTS (
    SELECT 1
    FROM skill_group sg
    WHERE sg.name = v.name
);

WITH skill_values(group_name, skill_name) AS (
    VALUES
        -- Языки программирования
        ('Языки программирования', 'Java'),
        ('Языки программирования', 'Kotlin'),
        ('Языки программирования', 'Python'),
        ('Языки программирования', 'JavaScript'),
        ('Языки программирования', 'TypeScript'),
        ('Языки программирования', 'Go'),
        ('Языки программирования', 'C'),
        ('Языки программирования', 'C++'),
        ('Языки программирования', 'C#'),
        ('Языки программирования', 'Rust'),
        ('Языки программирования', 'PHP'),
        ('Языки программирования', 'Ruby'),
        ('Языки программирования', 'Scala'),
        ('Языки программирования', 'Groovy'),
        ('Языки программирования', 'Swift'),
        ('Языки программирования', 'Objective-C'),
        ('Языки программирования', 'Dart'),
        ('Языки программирования', 'SQL'),
        ('Языки программирования', 'Bash / Shell'),
        ('Языки программирования', 'PowerShell'),
        ('Языки программирования', 'R'),
        ('Языки программирования', 'MATLAB'),
        ('Языки программирования', 'Perl'),
        ('Языки программирования', 'Lua'),
        ('Языки программирования', 'Elixir'),
        ('Языки программирования', 'Erlang'),
        ('Языки программирования', 'Haskell'),
        ('Языки программирования', 'F#'),
        ('Языки программирования', 'Visual Basic .NET'),

        -- Бекенд фреймворки
        ('Бекенд фреймворки', 'Spring Framework'),
        ('Бекенд фреймворки', 'Spring MVC'),
        ('Бекенд фреймворки', 'Spring WebFlux'),
        ('Бекенд фреймворки', 'Spring Security'),
        ('Бекенд фреймворки', 'Spring Data'),
        ('Бекенд фреймворки', 'Spring Cloud'),
        ('Бекенд фреймворки', 'Spring Batch'),
        ('Бекенд фреймворки', 'Hibernate / JPA'),
        ('Бекенд фреймворки', 'Jakarta EE'),
        ('Бекенд фреймворки', 'Jakarta REST / JAX-RS'),
        ('Бекенд фреймворки', 'Quarkus'),
        ('Бекенд фреймворки', 'Micronaut'),
        ('Бекенд фреймворки', 'Vert.x'),
        ('Бекенд фреймворки', 'Maven'),
        ('Бекенд фреймворки', 'Gradle'),
        ('Бекенд фреймворки', '.NET'),
        ('Бекенд фреймворки', 'ASP.NET Core'),
        ('Бекенд фреймворки', 'Entity Framework Core'),
        ('Бекенд фреймворки', 'LINQ'),
        ('Бекенд фреймворки', 'NuGet'),
        ('Бекенд фреймворки', 'Node.js'),
        ('Бекенд фреймворки', 'Express.js'),
        ('Бекенд фреймворки', 'NestJS'),
        ('Бекенд фреймворки', 'Fastify'),
        ('Бекенд фреймворки', 'Koa'),
        ('Бекенд фреймворки', 'Deno'),
        ('Бекенд фреймворки', 'Bun'),
        ('Бекенд фреймворки', 'Django'),
        ('Бекенд фреймворки', 'Flask'),
        ('Бекенд фреймворки', 'FastAPI'),
        ('Бекенд фреймворки', 'SQLAlchemy'),
        ('Бекенд фреймворки', 'Celery'),
        ('Бекенд фреймворки', 'Alembic'),
        ('Бекенд фреймворки', 'Laravel'),
        ('Бекенд фреймворки', 'Symfony'),
        ('Бекенд фреймворки', 'Yii'),
        ('Бекенд фреймворки', 'Ruby on Rails'),
        ('Бекенд фреймворки', 'Sinatra'),
        ('Бекенд фреймворки', 'Gin'),
        ('Бекенд фреймворки', 'Echo'),
        ('Бекенд фреймворки', 'Fiber'),
        ('Бекенд фреймворки', 'Actix'),
        ('Бекенд фреймворки', 'Tokio'),
        ('Бекенд фреймворки', 'Rocket'),
        ('Бекенд фреймворки', 'Boost'),
        ('Бекенд фреймворки', 'Qt'),
        ('Бекенд фреймворки', 'gRPC'),

        -- Фронтенд фреймворки
        ('Фронтенд фреймворки', 'HTML'),
        ('Фронтенд фреймворки', 'CSS'),
        ('Фронтенд фреймворки', 'SCSS / Sass'),
        ('Фронтенд фреймворки', 'Less'),
        ('Фронтенд фреймворки', 'React'),
        ('Фронтенд фреймворки', 'Vue.js'),
        ('Фронтенд фреймворки', 'Angular'),
        ('Фронтенд фреймворки', 'Next.js'),
        ('Фронтенд фреймворки', 'Nuxt.js'),
        ('Фронтенд фреймворки', 'Svelte'),
        ('Фронтенд фреймворки', 'SvelteKit'),
        ('Фронтенд фреймворки', 'Redux'),
        ('Фронтенд фреймворки', 'MobX'),
        ('Фронтенд фреймворки', 'RxJS'),
        ('Фронтенд фреймворки', 'Webpack'),
        ('Фронтенд фреймворки', 'Vite'),
        ('Фронтенд фреймворки', 'Babel'),
        ('Фронтенд фреймворки', 'ESLint'),
        ('Фронтенд фреймворки', 'npm'),
        ('Фронтенд фреймворки', 'Yarn'),
        ('Фронтенд фреймворки', 'pnpm'),
        ('Фронтенд фреймворки', 'Tailwind CSS'),
        ('Фронтенд фреймворки', 'Bootstrap'),
        ('Фронтенд фреймворки', 'Material UI'),
        ('Фронтенд фреймворки', 'Storybook'),
        ('Фронтенд фреймворки', 'Web Components'),
        ('Фронтенд фреймворки', 'Three.js'),
        ('Фронтенд фреймворки', 'WebAssembly'),
        ('Фронтенд фреймворки', 'Thymeleaf'),

        -- Мобильные фреймворки
        ('Мобильные фреймворки', 'Android'),
        ('Мобильные фреймворки', 'Android SDK'),
        ('Мобильные фреймворки', 'Kotlin Multiplatform'),
        ('Мобильные фреймворки', 'Jetpack Compose'),
        ('Мобильные фреймворки', 'iOS SDK'),
        ('Мобильные фреймворки', 'SwiftUI'),
        ('Мобильные фреймворки', 'UIKit'),
        ('Мобильные фреймворки', 'Combine'),
        ('Мобильные фреймворки', 'Core Data'),
        ('Мобильные фреймворки', 'Flutter'),
        ('Мобильные фреймворки', 'React Native'),
        ('Мобильные фреймворки', 'Xamarin'),
        ('Мобильные фреймворки', '.NET MAUI'),
        ('Мобильные фреймворки', 'Ionic'),
        ('Мобильные фреймворки', 'Cordova'),
        ('Мобильные фреймворки', 'Firebase'),
        ('Мобильные фреймворки', 'App Store Connect'),
        ('Мобильные фреймворки', 'Google Play Console'),

        -- Хранилища
        ('Хранилища', 'PostgreSQL'),
        ('Хранилища', 'MySQL'),
        ('Хранилища', 'MariaDB'),
        ('Хранилища', 'Oracle Database'),
        ('Хранилища', 'Microsoft SQL Server'),
        ('Хранилища', 'SQLite'),
        ('Хранилища', 'MongoDB'),
        ('Хранилища', 'Redis'),
        ('Хранилища', 'Elasticsearch'),
        ('Хранилища', 'OpenSearch'),
        ('Хранилища', 'Cassandra'),
        ('Хранилища', 'ScyllaDB'),
        ('Хранилища', 'ClickHouse'),
        ('Хранилища', 'Greenplum'),
        ('Хранилища', 'CockroachDB'),
        ('Хранилища', 'TimescaleDB'),
        ('Хранилища', 'InfluxDB'),
        ('Хранилища', 'Neo4j'),
        ('Хранилища', 'DynamoDB'),
        ('Хранилища', 'Amazon RDS'),
        ('Хранилища', 'Amazon Aurora'),
        ('Хранилища', 'Firestore'),
        ('Хранилища', 'Snowflake'),
        ('Хранилища', 'BigQuery'),
        ('Хранилища', 'Redshift'),
        ('Хранилища', 'Prisma'),
        ('Хранилища', 'Flyway'),
        ('Хранилища', 'Liquibase'),

        -- Интеграции
        ('Интеграции', 'Apache Kafka'),
        ('Интеграции', 'Kafka Streams'),
        ('Интеграции', 'RabbitMQ'),
        ('Интеграции', 'Apache Pulsar'),
        ('Интеграции', 'NATS'),
        ('Интеграции', 'ActiveMQ'),
        ('Интеграции', 'IBM MQ'),
        ('Интеграции', 'MQTT'),
        ('Интеграции', 'WebSocket'),
        ('Интеграции', 'GraphQL Subscriptions'),
        ('Интеграции', 'Debezium'),
        ('Интеграции', 'Apache Camel'),
        ('Интеграции', 'MuleSoft'),
        ('Интеграции', 'ETL'),
        ('Интеграции', 'API Gateway'),

        -- SRE
        ('SRE', 'Docker'),
        ('SRE', 'Kubernetes'),
        ('SRE', 'Helm'),
        ('SRE', 'Terraform'),
        ('SRE', 'OpenTofu'),
        ('SRE', 'Ansible'),
        ('SRE', 'Chef'),
        ('SRE', 'Puppet'),
        ('SRE', 'Jenkins'),
        ('SRE', 'GitLab CI/CD'),
        ('SRE', 'GitHub Actions'),
        ('SRE', 'CircleCI'),
        ('SRE', 'Argo CD'),
        ('SRE', 'Flux CD'),
        ('SRE', 'AWS'),
        ('SRE', 'Microsoft Azure'),
        ('SRE', 'Google Cloud Platform'),
        ('SRE', 'Yandex Cloud'),
        ('SRE', 'Cloudflare'),
        ('SRE', 'Linux'),
        ('SRE', 'Unix'),
        ('SRE', 'Nginx'),
        ('SRE', 'Apache HTTP Server'),
        ('SRE', 'HAProxy'),
        ('SRE', 'Envoy'),
        ('SRE', 'Istio'),
        ('SRE', 'Linkerd'),
        ('SRE', 'Prometheus'),
        ('SRE', 'Grafana'),
        ('SRE', 'Loki'),
        ('SRE', 'Jaeger'),
        ('SRE', 'OpenTelemetry'),
        ('SRE', 'ELK Stack'),
        ('SRE', 'Filebeat'),
        ('SRE', 'Logstash'),
        ('SRE', 'Vault'),
        ('SRE', 'Consul'),
        ('SRE', 'MinIO'),
        ('SRE', 'CDN'),
        ('SRE', 'Serverless'),
        ('SRE', 'FaaS'),
        ('SRE', 'CI/CD'),

        -- Data Engineering & ML
        ('ML', 'Apache Spark'),
        ('ML', 'PySpark'),
        ('ML', 'Apache Hadoop'),
        ('ML', 'Apache Hive'),
        ('ML', 'Apache Airflow'),
        ('ML', 'dbt'),
        ('ML', 'Apache Flink'),
        ('ML', 'Apache Beam'),
        ('ML', 'Airbyte'),
        ('ML', 'Fivetran'),
        ('ML', 'Dagster'),
        ('ML', 'Prefect'),
        ('ML', 'Pandas'),
        ('ML', 'NumPy'),
        ('ML', 'SciPy'),
        ('ML', 'scikit-learn'),
        ('ML', 'TensorFlow'),
        ('ML', 'PyTorch'),
        ('ML', 'Keras'),
        ('ML', 'MLflow'),
        ('ML', 'Jupyter'),
        ('ML', 'Apache Superset'),
        ('ML', 'Tableau'),
        ('ML', 'Power BI'),
        ('ML', 'Data Warehousing'),
        ('ML', 'Data Lake'),
        ('ML', 'Delta Lake'),
        ('ML', 'Apache Iceberg'),

        -- QA & Testing
        ('QA', 'Unit Testing'),
        ('QA', 'Integration Testing'),
        ('QA', 'End-to-End Testing'),
        ('QA', 'Test Automation'),
        ('QA', 'Selenium'),
        ('QA', 'Cypress'),
        ('QA', 'Playwright'),
        ('QA', 'WebdriverIO'),
        ('QA', 'Appium'),
        ('QA', 'Postman'),
        ('QA', 'Newman'),
        ('QA', 'JMeter'),
        ('QA', 'Gatling'),
        ('QA', 'Locust'),
        ('QA', 'Pytest'),
        ('QA', 'unittest'),
        ('QA', 'Jest'),
        ('QA', 'Vitest'),
        ('QA', 'Mocha'),
        ('QA', 'Chai'),
        ('QA', 'Jasmine'),
        ('QA', 'JUnit'),
        ('QA', 'TestNG'),
        ('QA', 'Mockito'),
        ('QA', 'AssertJ'),
        ('QA', 'Testcontainers'),
        ('QA', 'Cucumber'),
        ('QA', 'Allure'),
        ('QA', 'SonarQube'),

        -- Security
        ('Security', 'OAuth 2.0'),
        ('Security', 'OpenID Connect'),
        ('Security', 'JWT'),
        ('Security', 'SAML'),
        ('Security', 'TLS / SSL'),
        ('Security', 'HTTPS'),
        ('Security', 'OWASP Top 10'),
        ('Security', 'Penetration Testing'),
        ('Security', 'SAST'),
        ('Security', 'DAST'),
        ('Security', 'Secrets Management'),
        ('Security', 'Keycloak'),
        ('Security', 'LDAP'),
        ('Security', 'Active Directory'),
        ('Security', 'RBAC'),
        ('Security', 'IAM'),

        -- Архитектура
        ('Архитектура', 'Microservices'),
        ('Архитектура', 'Monolith'),
        ('Архитектура', 'Modular Monolith'),
        ('Архитектура', 'Event-Driven Architecture'),
        ('Архитектура', 'Domain-Driven Design'),
        ('Архитектура', 'Clean Architecture'),
        ('Архитектура', 'Hexagonal Architecture'),
        ('Архитектура', 'SOLID'),
        ('Архитектура', 'Design Patterns'),
        ('Архитектура', 'Refactoring'),
        ('Архитектура', 'TDD'),
        ('Архитектура', 'BDD'),
        ('Архитектура', 'CQRS'),
        ('Архитектура', 'Event Sourcing'),
        ('Архитектура', 'Distributed Systems'),
        ('Архитектура', 'High Load'),
        ('Архитектура', 'Scalability'),
        ('Архитектура', 'Fault Tolerance'),
        ('Архитектура', 'Observability'),
        ('Архитектура', 'Caching'),
        ('Архитектура', 'API Design'),
        ('Архитектура', 'REST API'),
        ('Архитектура', 'GraphQL'),
        ('Архитектура', 'SOAP'),
        ('Архитектура', 'JSON'),
        ('Архитектура', 'XML'),
        ('Архитектура', 'YAML'),
        ('Архитектура', 'Protocol Buffers'),
        ('Архитектура', 'OpenAPI / Swagger'),
        ('Архитектура', 'AsyncAPI'),

        -- Инструменты
        ('Инструменты', 'Git'),
        ('Инструменты', 'GitHub'),
        ('Инструменты', 'GitLab'),
        ('Инструменты', 'Bitbucket'),
        ('Инструменты', 'Jira'),
        ('Инструменты', 'Confluence'),
        ('Инструменты', 'Trello'),
        ('Инструменты', 'Slack'),
        ('Инструменты', 'Notion'),
        ('Инструменты', 'Figma'),
        ('Инструменты', 'IntelliJ IDEA'),
        ('Инструменты', 'Visual Studio Code'),
        ('Инструменты', 'Visual Studio'),
        ('Инструменты', 'DBeaver'),
        ('Инструменты', 'DataGrip'),
        ('Инструменты', 'pgAdmin'),
        ('Инструменты', 'Make'),
        ('Инструменты', 'CMake')
)
INSERT INTO skill (skill_group_id, name)
SELECT sg.id, sv.skill_name
FROM skill_values sv
         JOIN skill_group sg ON sg.name = sv.group_name
WHERE NOT EXISTS (
    SELECT 1
    FROM skill s
    WHERE lower(s.name) = lower(sv.skill_name)
);
