spring.application.name=vitrina-service
server.port=8087
spring.datasource.url=jdbc:postgresql://localhost:5434/data-mart
spring.datasource.username=user
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate/JPA configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Liquibase configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
spring.liquibase.default-schema=public

debezium.api.url = http://localhost:8090/connectors
debezium.connector.name = users-cdc-connector
debezium.task.connector.name = task-cdc-connector

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=analytics-cdc-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.config.import=optional:file:.env[.properties]

security.jwt.secret_key = ${JWT_SECRET_KEY}
security.jwt.access_token_expiration = ${JWT_ACCESS_TOKEN_EXPIRATION}
security.jwt.refresh_token_expiration = ${JWT_REFRESH_TOKEN_EXPIRATION}
authorization.service.url = ${AUTHORIZATION_SERVICE_URL}
webclient.timeout = ${WEBCLIENT_TIMEOUT}

front.server.origins = ${FRONT_SERVER_URL}
